# Generated by Django 5.0.6 on 2025-04-05 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField()),
                ('username', models.CharField(unique=True)),
                ('name', models.CharField()),
                ('password', models.CharField()),
                ('position', models.CharField()),
            ],
            options={
                'db_table': 'Admin',
                'db_table_comment': 'Admin credentials for secure access.',
            },
        ),
        migrations.CreateModel(
            name='LostItem',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField()),
                ('category', models.CharField(choices=[('EL', 'Electronics'), ('PB', 'Personal Belongings'), ('CL', 'Clothing & Accessories'), ('JW', 'Jewelry'), ('MS', 'Miscellaneous')], default='MS', max_length=2)),
                ('status', models.CharField(choices=[('UC', 'Unclaimed'), ('CL', 'Claimed')], default='UC', max_length=2)),
                ('description', models.TextField()),
                ('location_found', models.TextField()),
                ('photo_url', models.CharField()),
                ('created_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'LostItem',
                'db_table_comment': 'Lost Item Attributes',
            },
        ),
    ]
