# Generated by Django 5.0.6 on 2025-04-07 05:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField()),
                ('email', models.CharField(unique=True)),
                ('number', models.CharField()),
                ('password', models.CharField()),
            ],
            options={
                'db_table': 'Admin',
                'db_table_comment': 'Admin credentials for secure access.',
            },
        ),
        migrations.CreateModel(
            name='LostItem',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField()),
                ('description', models.TextField()),
                ('category', models.CharField(choices=[('EL', 'Electronics'), ('PB', 'Personal Belongings'), ('CL', 'Clothing & Accessories'), ('JW', 'Jewelry'), ('MS', 'Miscellaneous')], default='MS', max_length=2)),
                ('date_found', models.DateField()),
                ('time_found', models.TimeField()),
                ('location_found', models.TextField()),
                ('photo_url', models.URLField()),
                ('status', models.CharField(choices=[('UC', 'Unclaimed'), ('CL', 'Claimed')], default='UC', max_length=2)),
            ],
            options={
                'db_table': 'LostItem',
                'db_table_comment': 'Lost Item Attributes',
            },
        ),
        migrations.CreateModel(
            name='ClaimForm',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('claim_date', models.DateField()),
                ('name', models.CharField()),
                ('ownership_photo', models.URLField()),
                ('number', models.CharField()),
                ('media', models.URLField()),
                ('item_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.lostitem')),
            ],
        ),
    ]
