# Generated by Django 5.0.6 on 2025-04-07 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lostitem',
            name='photo_url',
            field=models.CharField(),
        ),
    ]
