# Generated by Django 5.0.6 on 2025-04-08 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='claimform',
            name='ownership_photo',
            field=models.CharField(),
        ),
    ]
