# Generated by Django 5.0.6 on 2025-04-07 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_lostitem_photo_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='claimform',
            name='detailed_description',
            field=models.TextField(default=None),
            preserve_default=False,
        ),
    ]
