# Generated by Django 5.0.6 on 2025-04-12 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_lostitem_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lostitem',
            name='category',
            field=models.CharField(choices=[('BA', 'Bags & Backpacks'), ('EL', 'Electronics'), ('EW', 'Eyewear'), ('FW', 'Footwear'), ('ID', 'IDs & Cards'), ('KY', 'Keys'), ('MS', 'Miscellaneous'), ('MB', 'Mobile Devices'), ('WT', 'Wallets & Purses'), ('WH', 'Watches & Jewerly')], default='MS', max_length=2),
        ),
    ]
