# Generated by Django 5.2 on 2025-04-13 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_lostitem_category'),
    ]

    operations = [
        migrations.AlterModelTableComment(
            name='claimform',
            table_comment='Claim Form Attributes',
        ),
        migrations.AlterField(
            model_name='claimform',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='claimform',
            name='number',
            field=models.CharField(max_length=11),
        ),
        migrations.AlterModelTable(
            name='claimform',
            table='ClaimForm',
        ),
    ]
