# Generated by Django 5.0.6 on 2025-04-21 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_admin_date_joined_admin_first_name_admin_groups_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lostitem',
            name='claim_id',
            field=models.IntegerField(default=None, null=True),
        ),
    ]
