# Generated by Django 5.0.6 on 2025-04-21 07:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_lostitem_claim_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lostitem',
            name='claim_id',
        ),
        migrations.AddField(
            model_name='lostitem',
            name='accepted_claim',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accepted_claim', to='core.claimform'),
        ),
        migrations.AlterField(
            model_name='claimform',
            name='item_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='claims', to='core.lostitem'),
        ),
    ]
